---
engines:
#  reek:
#    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- test/**/*
- example.rb